### ISSUE TITLE
Cannot make project on Mac OS X

### ISSUE THREAD

**Issue by ibalashov** [davidrmiller/neural2d#11] opened 2015-04-11 19:47 UTC
Make project on OS X gives the error below. Any ideas if this could be fixed?

OS X 10.9.5
gcc: stable 4.9.2 (bottled)

```
neural2d$ make
g++ -std=c++11 -pthread -g -O2 -Wall -Wextra -pedantic -Wno-missing-field-initializers -c neural2d-core.cpp -o neural2d-core.o
neural2d-core.cpp:115:46: error: use of undeclared identifier 'tanh'
float transferFunctionTanh(float x) { return tanh(x); }
                                             ^
neural2d-core.cpp:116:62: error: use of undeclared identifier 'tanh'
float transferFunctionDerivativeTanh(float x) { return 1.0 - tanh(x) * tanh(x); }
                                                             ^
neural2d-core.cpp:116:72: error: use of undeclared identifier 'tanh'
float transferFunctionDerivativeTanh(float x) { return 1.0 - tanh(x) * tanh(x); }
                                                                       ^
neural2d-core.cpp:119:63: error: use of undeclared identifier 'exp'
float transferFunctionLogistic(float x) { return 1.0 / (1.0 + exp(-x)); }
                                                              ^
neural2d-core.cpp:120:60: error: use of undeclared identifier 'exp'
float transferFunctionDerivativeLogistic(float x) { return exp(-x) / pow((exp(-x) + 1.0), 2.0); }
                                                           ^
neural2d-core.cpp:120:75: error: use of undeclared identifier 'exp'
float transferFunctionDerivativeLogistic(float x) { return exp(-x) / pow((exp(-x) + 1.0), 2.0); }
                                                                          ^
neural2d-core.cpp:136:50: error: use of undeclared identifier 'exp'
float transferFunctionGaussian(float x) { return exp(-((x * x) / 2.0)); }
                                                 ^
neural2d-core.cpp:137:65: error: use of undeclared identifier 'exp'
float transferFunctionDerivativeGaussian(float x) { return -x * exp(-(x * x) / 2.0); }
                                                                ^
neural2d-core.cpp:1134:79: error: use of undeclared identifier 'sqrt'
                    connections.back().weight = ((randomFloat() * 2) - 1.0) / sqrt(maxNumSourceNeurons);
                                                                              ^
9 errors generated.
make: *** [neural2d-core.o] Error 1

$ brew info gcc
gcc: stable 4.9.2 (bottled)
```

**Comment by davidrmiller** [comment] 2015-04-11 20:31
Thanks for reporting this. It looks like we need to add "#include &lt;cmath&gt;" to the top of neural2d-core.cpp. (I do not have a Mac on which to test this. Please leave a comment here or open a new issue if that fails to fix the problem.)

**Comment by ibalashov** [comment] 2015-04-11 20:40
@davidrmiller Thanks! Adding the include got me past this error. However, now I'm getting:
```
neural2d$ make
g++ -std=c++11 -pthread -g -O2 -Wall -Wextra -pedantic -Wno-missing-field-initializers -c neural2d-core.cpp -o neural2d-core.o
g++ -std=c++11 -pthread -g -O2 -Wall -Wextra -pedantic -Wno-missing-field-initializers -c webserver.cpp -o webserver.o
webserver.cpp:229:12: error: invalid operands to binary expression ('int' and '__bind<int &, sockaddr *, unsigned long>')
    if (-1 == bind(socketFd, (struct sockaddr *)&stSockAddr, sizeof(stSockAddr))) {
        ~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [webserver.o] Error 1
```

**Comment by jeandudey** [comment] 2015-04-12 12:54
The cause of this error is that the code uses "using namespace std;" to solve this you have to change bind to ::bind.

**Comment by ibalashov** [comment] 2015-04-12 15:39
@jeandudey Thanks! It solved the problem, except the warning which I guess might be ignored:

```
clang: warning: argument unused during compilation: '-pthread'
```

**Comment by jeandudey** [comment] 2015-04-12 16:10
:+1:

**Comment by davidrmiller** [comment] 2015-04-12 18:12
I checked in 3f5372a6420fb38b3dea7090533d60d11afc72d8 to address the issue with the math and ::bind(). Thanks @jeandudey and @ibalashov for the contributions and testing.

**Closed by davidrmiller** 2015-04-12 18:12 UTC
